language: csharp

mono: none

dotnet: 2.2.100

solution: "./Escola.sln"
sudo: required

os:
-linux

script:
- dotnet restore
- dotnet build
- dotnet test ./Escola/Escola.Domain.Tests/Escola.Domain.Tests.csproj

service:
- docker


# before_install:
# - docker pull mcr.microsoft.com/dotnet/core/aspnet:2.2
# - docker ps